version: '3.8'

services:

  pgbouncer:
    image: edoburu/pgbouncer
    env_file:
      - env/db.env
    ports:
      - 6432:5432
    depends_on:
      - db
    networks:
      - db_layer

  backend:
    environment:
      - HOST=0.0.0.0
      - POSTGRES_HOST=pgbouncer
      - POSTGRES_PORT=6432
    ports:
      - 8000
    user: root
    networks:
      - proxy_back

  proxy:
    image: nginx:1.19
    env_file:
      - env/proxy.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/templates:/etc/nginx/templates
      - type: bind
        source: ./backend/static
        target: /usr/src/panda/static
      - type: bind
        source: ./backend/media
        target: /usr/src/panda/media
      - type: bind
        source: ./backend/ssl
        target: /usr/src/panda/ssl
    depends_on:
      - backend
    networks:
      - proxy_back

networks:
  proxy_back:
    driver: bridge
