version: '3.8'

services:

  db:
    image: postgres
    env_file:
      - env/db.env
    volumes:
      - /var/lib/postgresql/${PROJECT_NAME}:/var/lib/postgresql/data
    networks:
      - db_layer

  redis:
    image: redis:alpine
    networks:
      - db_layer

  backend:
    build:
      context: backend/.
      args:
        PROJECT_NAME: ${PROJECT_NAME}
    env_file:
      - env/common.env
      - env/back.env
      - env/db.env
    volumes:
      - ./backend:/usr/src/${PROJECT_NAME}
    depends_on:
      - db
      - redis
    networks:
      - db_layer

networks:
  db_layer:
    driver: bridge
