version: '3.8'

services:

  db:
    restart: unless-stopped

  redis:
    restart: unless-stopped

  pgbouncer:
    container_name: pgbouncer
    image: edoburu/pgbouncer:1.15.0
    env_file:
      - env/db.env
    ports:
      - 6432:5432
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - db_layer

  backend:
    environment:
      - POSTGRES_HOST=pgbouncer
      - POSTGRES_PORT=6432
    ports:
      - 8000
#    user: root
    volumes:
      # Volume
      - static:/usr/src/${PROJECT_NAME}/static_root
      # Bind
      - ./backend/media:/usr/src/${PROJECT_NAME}/media
    restart: unless-stopped
    networks:
      - proxy_back

  proxy:
    container_name: proxy
    image: nginx:1.19
    env_file:
      - env/common.env
    ports:
      - ${PROXY_PORT_HTTP}:80
      - ${PROXY_PORT_HTTPS}:443
    volumes:
      # Volume
      - static:/usr/src/${PROJECT_NAME}/static_root
      # Bind
      - ./proxy/templates:/etc/nginx/templates
      - ./ssl:/usr/src/${PROJECT_NAME}/ssl
      - ./backend/media:/usr/src/${PROJECT_NAME}/media
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - proxy_back

volumes:
  static:

networks:
  proxy_back:
    driver: bridge
