version: '3'

services:
  backend:
#    environment:
#      - DJANGO_DEBUG=1
    command:
#      [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
      ["daphne", "-e", "ssl:8000:privateKey=ssl/dev.local.key:certKey=ssl/dev.local.crt", "backend.asgi:application"]
    ports:
      - 8000:8000
