version: '3.8'

services:

  db:
    image: postgres
    env_file:
      - env/db.env
    networks:
      - db_layer

  backend:
    build: backend/.
    env_file:
      - env/back.env
      - env/db.env
    volumes:
      - ./backend:/usr/src/panda
    depends_on:
      - db
    networks:
      - db_layer

networks:
  db_layer:
    driver: bridge
