version: '3.8'

services:

  db:
    restart: always

  redis:
    restart: always

  pgbouncer:
    image: edoburu/pgbouncer
    env_file:
      - env/db.env
    ports:
      - 6432:5432
    restart: always
    depends_on:
      - db
    networks:
      - db_layer

  backend:
    environment:
      - POSTGRES_HOST=pgbouncer
      - POSTGRES_PORT=6432
    ports:
      - 8000
    user: root
    command:
      [ "daphne", "-b", "0.0.0.0", "-p", "8000", "backend.asgi:application" ]
    restart: always
    networks:
      - proxy_back

  proxy:
    image: nginx:1.19
    env_file:
      - env/common.env
    ports:
      - ${PROXY_PORT_V4}:80
      - ${PROXY_PORT_V6}:443
    volumes:
      - ./proxy/templates:/etc/nginx/templates
      - type: bind
        source: ./backend/static
        target: /usr/src/${PROJECT_NAME}/static
      - type: bind
        source: ./backend/media
        target: /usr/src/${PROJECT_NAME}/media
      - type: bind
        source: ./backend/ssl
        target: /usr/src/${PROJECT_NAME}/ssl
    restart: always
    depends_on:
      - backend
    networks:
      - proxy_back

networks:
  proxy_back:
    driver: bridge
