version: '3.8'

services:

  db:
    image: postgres
    env_file:
      - env/db.env
    volumes:
    - /var/lib/postgresql/hellopanda:/var/lib/postgresql/data
    networks:
      - db_layer

  redis:
    image: redis:alpine
    networks:
      - db_layer

  backend:
    build: backend/.
    env_file:
      - env/back.env
      - env/db.env
    volumes:
      - ./backend:/usr/src/panda
    depends_on:
      - db
      - redis
    networks:
      - db_layer
    command:
      [ "daphne", "-e", "ssl:8000:privateKey=ssl/dev.local.key:certKey=ssl/dev.local.crt", "backend.asgi:application" ]

networks:
  db_layer:
    driver: bridge
