version: '3.8'

services:

  backend:
    environment:
      - HOST=0.0.0.0
    ports:
      - 8000
    user: root
    networks:
      - proxy_back

  proxy:
    image: nginx:1.19
    env_file:
      - env/proxy.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/templates:/etc/nginx/templates
      - type: bind
        source: ./backend/static
        target: /usr/src/panda/static
      - type: bind
        source: ./backend/media
        target: /usr/src/panda/media
      - type: bind
        source: ./backend/ssl
        target: /usr/src/panda/ssl
    depends_on:
      - backend
    networks:
      - proxy_back

networks:
  proxy_back:
    driver: bridge
