version: '3.8'

services:

  db:
    restart: always

  redis:
    restart: always

  pgbouncer:
    image: edoburu/pgbouncer
    env_file:
      - env/db.env
    ports:
      - 6432:5432
    restart: always
    depends_on:
      - db
    networks:
      - db_layer

  backend:
    environment:
      - HOST=0.0.0.0
      - POSTGRES_HOST=pgbouncer
      - POSTGRES_PORT=6432
    ports:
      - 8000
    user: root
    command:
      [ "daphne", "-b", "0.0.0.0", "-p", "8000", "backend.asgi:application" ]
    restart: always
    networks:
      - proxy_back

  proxy:
    image: nginx:1.19
    env_file:
      - env/proxy.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/templates:/etc/nginx/templates
      - type: bind
        source: ./backend/static
        target: /usr/src/hello_panda/static
      - type: bind
        source: ./backend/media
        target: /usr/src/hello_panda/media
      - type: bind
        source: ./backend/ssl
        target: /usr/src/hello_panda/ssl
    restart: always
    depends_on:
      - backend
    networks:
      - proxy_back

networks:
  proxy_back:
    driver: bridge
