version: '3.8'

services:

  db:
    container_name: db
    image: postgres:13
    env_file:
      - env/db.env
    volumes:
      # Bind
      - /var/lib/postgresql/${PROJECT_NAME}:/var/lib/postgresql/data
    networks:
      - db_layer

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - db_layer

  backend:
    container_name: backend
    build:
      context: backend/.
      args:
        PROJECT_NAME: ${PROJECT_NAME}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        DEBUG: ${DEBUG}
    env_file:
      - env/common.env
      - env/back.env
      - env/db.env
    command:
      sh -c "
        python3 -c \"import redis;r=redis.Redis(host='redis',port='6379');r.flushall()\"
        && python3 manage.py collectstatic -c --no-input
        && daphne -b 0.0.0.0 -p 8000 backend.asgi:application
      "
    depends_on:
      - db
      - redis
    networks:
      - db_layer


networks:
  db_layer:
    driver: bridge
